import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar/Navbar";
// import Footer from "../../components/Footer";
import BottomNav from "../../components/global/BottomNav";
import { Toaster } from "@/components/ui/sonner";
import Providers from "./Providers";
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "Infinity Wears",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          suppressHydrationWarning
          className={`${montserrat.className} bg-white`}
        >
          <Providers>
            <Navbar />
            <main className=" bg-white text-black">{children}</main>
            {/* <Footer /> */}
            <div className="sm:hidden">
              <BottomNav />
            </div>
            <Toaster />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
