import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar/Navbar";
import Footer from "../../components/footer/Footer";
import { Toaster } from "@/components/ui/sonner";
import Providers from "./Providers";
import BottomNavWrapper from "../../components/global/BottomNavWrapper";
import { ClientOnly } from "../../components/Navbar/NavWrapper";
import NavbarWrapper from "../../components/Navbar/NavbarWrapper";
import { Suspense } from "react";
import NavbarSkeleton from "../../components/Navbar/NavSkeleton";
import FooterWrapper from "../../components/footer/FooterWrapper";
import { auth } from "@clerk/nextjs/server";
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "Infinity Wears",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { sessionClaims } = await auth();
  const isAdmin = sessionClaims?.metadata?.role === "admin";
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          suppressHydrationWarning
          className={`${montserrat.className} bg-white`}
        >
          <Providers>
            {/* <ClientOnly> */}

            <Suspense fallback={<NavbarSkeleton />}>
              <NavbarWrapper />
            </Suspense>
            {/* </ClientOnly> */}
            <main className=" bg-white text-black">{children}</main>
            <FooterWrapper />
            <div className="lg:hidden fixed bottom-0 left-0 right-0 z-999 flex justify-center pointer-events-none">
              <BottomNavWrapper isAdmin />
            </div>
            <Toaster />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
