import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar/Navbar";
// import Footer from "../../components/Footer";
import Providers from "./Providers";
import BottomNav from "../../components/global/BottomNav";
import { Toaster } from "@/components/ui/sonner";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "Infinity Wears",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={montserrat.className}>
        <Providers>
          <Navbar />

          <main className=" bg-white text-black">{children}</main>
          {/* <Footer /> */}
          <div className="sm:hidden">
            <BottomNav />
          </div>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
